FROM ubuntu:bionic

RUN apt -yqq update --no-install-recommends >/dev/null
RUN apt install --no-install-recommends -yqq git curl tar gzip build-essential ca-certificates debhelper devscripts devscripts dh-systemd fakeroot python-all python-docutils iproute2 python-ipaddr python-argcomplete python-setuptools dh-python
