version: '2'
services:
  nosu-pkg-mlnx-mft:
    build: ./
    image: nosu-pkg-mlnx-mft
    privileged: true
    volumes:
      - "./kernel:/tmp/kernel"
      - ".:/mnt"
    working_dir: /mnt
    command: [ "/mnt/build.sh", "/mnt/${ENVFILE}" ]
