version: '2'
services:
  nosu-pkg-sosreport:
    build: ./
    image: nosu-pkg-sosreport
    privileged: true
    volumes:
      - ".:/mnt"
    working_dir: /mnt
    command: [ "/mnt/build.sh", "/mnt/${ENVFILE}" ]
